### ISSUE TITLE
Failed to install pod

### ISSUE THREAD

**Issue by AlexanderOsokin** [xpring-eng/XpringKit#111]
Hello! 
First, there was a problem with the submodules. I had to add ssh keys to make cocoapods clone submodules. Now, I can't install pod due to compilation issues. Maybe you can add the precompiled binaries to facilitate pod installation? A lot of time needs to be spent just to install the pod. In the future, we will have many problems with our CI-machine. Thank you 

```
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)
Installing SwiftGRPC (0.10.0)
Installing XpringKit (1.1.3)
[!] /bin/bash -c 
set -e
git submodule update --init --recursive && ./scripts/bundle_js.sh && ./scripts/regenerate_protos.sh

Submodule path 'xpring-common-js': checked out '344737a1652c55120c2b1659315d8c760171f111'
Submodule path 'xpring-common-js/xpring-common-protocol-buffers': checked out '6f983e508bee6d358156776561e884719275d9f0'
Submodule path 'xpring-common-protocol-buffers': checked out '5a345fd40b468f824d6ad1bdb88e8db3f41354b4'
Bundling JS
>> Installing Node Dependencies

> fsevents@1.2.9 install /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> tiny-secp256k1@1.1.3 install /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.3 build /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/tiny-secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/native/addon.o
secp256k1 bindings compilation fail. Pure JS implementation will be used.

> grpc@1.24.2 install /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" is installed via remote

> core-js@2.6.9 postinstall /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/ripple-binary-codec/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 961 packages from 1267 contributors and audited 7904 packages in 19.674s
found 13 vulnerabilities (4 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details
>> Done Installing Node Dependencies
>> Running Webpack.

> xpring-common-js@1.1.5 webpack /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js
> npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack


> xpring-common-js@1.1.5 clean /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js
> rm -rf ./generated ./dist ./build

Regenerating Protocol Buffers
Submodule 'xpring-common-js' (git@github.com:xpring-eng/xpring-common-js) registered for path 'xpring-common-js'
Submodule 'xpring-common-protocol-buffers' (git@github.com:xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-protocol-buffers'
Cloning into '/Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js'...
Cloning into '/Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-protocol-buffers'...
Submodule 'xpring-common-protocol-buffers' (http://github.com/xpring-eng/xpring-common-protocol-buffers) registered for path 'xpring-common-js/xpring-common-protocol-buffers'
Cloning into '/Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/xpring-common-protocol-buffers'...
warning: redirecting to https://github.com/xpring-eng/xpring-common-protocol-buffers/
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.8.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
../native/addon.cpp:240:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:320:34: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                strict = info[3]->BooleanValue(Nan::GetCurrentContext()).FromJust();
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/.../Library/Caches/node-gyp/13.8.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:82:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:142:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<2, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<2>(info, pA);
                           ^
/Users/.../Library/Caches/node-gyp/13.8.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:82:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:174:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<1>(info, p);
                           ^
/Users/.../Library/Caches/node-gyp/13.8.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:89:36: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:189:21: note: in instantiation of function template specialization '(anonymous namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value> >' requested here
        const auto flags = assumeCompression<1>(info);
                           ^
/Users/.../Library/Caches/node-gyp/13.8.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
../native/addon.cpp:87:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
4 warnings and 4 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/.../Library/Caches/CocoaPods/Pods/Release/XpringKit/1.1.3-42df3/xpring-common-js/node_modules/tiny-secp256k1
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-02-10T20_05_52_869Z-debug.log
node-pre-gyp WARN Using needle for node-pre-gyp https download 
./scripts/regenerate_protos.sh: line 16: grpc_tools_node_protoc: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! xpring-common-js@1.1.5 webpack: `npm run clean && ./scripts/regenerate_protos.sh && tsc && npx webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the xpring-common-js@1.1.5 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-02-10T20_05_55_617Z-debug.log
```

**Comment by keefertaylor** [comment]
Hey! 

Sorry that we haven't gotten back to you. In later version of this library, we check in generated artifacts so as not to require users to have all the required tooling that the SDK developers use.  Looks like you're trying to use 1.1 whereas the latest version is 1.3. Rather than try to diagnose this problem, I'd recommend upgrading to the latest. 

Apologies for the frustration - I know it's a bummer. 

If you're explicitly building from source, I'd recommend following the instructions in [CONTRIBUTING.md](https://github.com/xpring-eng/XpringKit/blob/master/CONTRIBUTING.md#building-the-library).

**Comment by keefertaylor** [comment]
Closing this out as I haven't heard anything here and I believe the issue to be resolved. Please re-open if you're still having trouble.
